# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: ENS-Indexer
networks:
  - id: 1
    start_block: 0
    contracts:
      - name: ENSRegistryWithFallback
        address:
          - "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"
          - "0x314159265dD8dbb310642f98f50C066173C1259b"
        handler: src/ENSRegistryEventHandlers.ts
        events:
          - event: NewOwner(bytes32 indexed node, bytes32 indexed label, address owner)
          - event: NewResolver(bytes32 indexed node, address resolver)
          - event: NewTTL(bytes32 indexed node, uint64 ttl)
          - event: Transfer(bytes32 indexed node, address owner)
      - name: BaseRegistrar
        address:
          - "0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85"
        handler: src/RegistrarControllerEventHandler.ts
        events:
          - event: NameRegistered(uint256 indexed id, address indexed owner, uint256 expires)
          - event: NameRenewed(uint256 indexed id, uint256 expires)
          - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - name: EthRegistrarControllerOld
        address:
          - "0x283Af0B28c62C092C9727F1Ee09c02CA627EB7F5"
        handler: src/RegistrarControllerEventHandler.ts
        events:
          - event: NameRegistered(string name, bytes32 indexed label, address indexed owner, uint256 cost, uint256 expires)
          - event: NameRenewed(string name, bytes32 indexed label, uint256 cost, uint256 expires)
      - name: ETHRegistrarController
        address:
          - "0x253553366Da8546fC250F225fe3d25d0C782303b"
        handler: src/RegistrarControllerEventHandler.ts
        events:
          - event: NameRegistered(string name, bytes32 indexed label, address indexed owner, uint256 baseCost, uint256 premium, uint256 expires)
          - event: NameRenewed(string name, bytes32 indexed label, uint256 cost, uint256 expires)
      - name: NameWrapper
        address:
          - "0xD4416b13d2b3a9aBae7AcD5D6C2BbDBE25686401"
        handler: src/NameWrapperHandler.ts
        events:
          - event: ExpiryExtended(bytes32 indexed node, uint64 expiry)
          - event: FusesSet(bytes32 indexed node, uint32 fuses)
          - event: NameUnwrapped(bytes32 indexed node, address owner)
          - event: NameWrapped(bytes32 indexed node, bytes name, address owner, uint32 fuses, uint64 expiry)
          - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
          - event: TransferBatch(address indexed operator, address indexed from, address indexed to, uint256[] ids, uint256[] values)
          - event: TransferSingle(address indexed operator, address indexed from, address indexed to, uint256 id, uint256 value)

field_selection:
  transaction_fields:
    - "from"
    - "to"
    - "hash"
    - "transactionIndex"
